/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 2012-7-20, 21:01:46
 */
package org.sysu.igem.utils;

import java.awt.Color;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.jdom.Element;

/**
 *
 * @author Administrator
 */
public class testBiobreak extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public testBiobreak() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DrawButtons(JPanel panel)
    {
        int left=0;
        int top=0;
        int tempright=0;
        final int separatWidth=45;
        ReadXml read = new ReadXml();
        List<JButton> buttons=new ArrayList<JButton>();
        List<Element> l = read.readXMLContent("genome.xml");
        int i=-1;
        for (Element el : l) {         
             i++;
             int buttonWidth=el.getChildText("product").length()*5;             
             String buttonText = "<html><font style=\"color:white;\">"+el.getChildText("product")+"</font></html>";
             JButton button1=new JButton(buttonText);
             button1.setFocusable(false);
             button1.setBackground(Color.red);  
             button1.setBounds(left,top,buttonWidth , 50);
             button1.setVisible(true);
             panel.add(button1);            
             buttons.add(button1);
             tempright=left+el.getChildText("product").length()*5;
             if(i<l.size()-1)
                this.AddLine(panel, tempright, separatWidth, top+50/2);
             left=left+buttonWidth+separatWidth;                    
        }
        jScrollPane1.setViewportView(panel);
    }
    public void AddLine(JPanel panel,int left,int width,int top)
    {
        final int height=10;
        JButton button=new JButton();
        button.setBounds(left, top, width, 10);
        button.setBackground(Color.black);
        panel.add(button);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                testBiobreak frame=new testBiobreak();
                frame.DrawButtons(new JPanel());   
  
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
