/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * riboswitchJFrame.java
 *
 * Created on 2012-10-20, 20:26:35
 */
package org.sysu.igem.riboswitch;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import org.jdom.Element;
import org.sysu.igem.newUI.CustomScrollBarUI;
import org.sysu.igem.newUI.IComboBoxRenderer;
import org.sysu.igem.newUI.IComboBoxUI;
import org.sysu.igem.utils.ReadXml;

/**
 *
 * @author Guo Jiexin
 */
public class riboswitchJFrame extends javax.swing.JFrame {
    public List<String> AptName = new ArrayList<String>();
    public List<String> Aptseq = new ArrayList<String>();
    public List<String> Target = new ArrayList<String>();
    public List<String> targetType = new ArrayList<String>();
    public Riboswitch riboswitch = null;
    public int aptSelect = 0;
    /** Creates new form riboswitchJFrame */
    public riboswitchJFrame() {
        initComponents();
        this.initRiboswitch();
    }
    public void initRiboswitch() {
        riboswitchTarNameTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                riboswitchJFrame.this.refreshJList1();
            }

            public void removeUpdate(DocumentEvent e) {
                riboswitchJFrame.this.refreshJList1();
            }

            public void changedUpdate(DocumentEvent e) {
                riboswitchJFrame.this.refreshJList1();
            }
        });
        this.readAptamer();
    }
    /**
     *
     */
    public void readAptamer() {
        ReadXml read = new ReadXml();
        List<Element> l = new ArrayList<Element>();
        l = read.readXMLContent("aptamer.xml");
        System.out.println(l.size());
        for (int i = 0; i < l.size(); i++) {            
            Element temp = l.get(i).getChild("target");
            if (temp != null) {
                Target.add(temp.getText());
                temp = l.get(i).getChild("targettype");
                targetType.add(temp.getText());
                temp = l.get(i).getChild("aptamers");
                temp = temp.getChild("aptamer");
                AptName.add(temp.getChild("name").getText());
                Aptseq.add(temp.getChild("seq").getText());
            }
        }
    }
    public List<String> getRiboswitchTargetByInput() {
        List<String> toReturn = new ArrayList<String>();
        for (int i = 0; i < Target.size(); i++) {
            //when targettype=="" means it is all type
            //or else targetType equals riboswitchTypeComboBox.getSelectedItem()
            if (targetType.get(i).length() == 0 || targetType.get(i).indexOf((String) this.riboswitchTypeComboBox.getSelectedItem()) >= 0) {
                String userInput = this.riboswitchTarNameTextField.getText();
                //target userInput include userinput
                //and both to lowercase compare
                if (Target.get(i).toLowerCase().indexOf(userInput.toLowerCase()) >= 0) {
                    if (!toReturn.contains(this.Target.get(i))) {
                        toReturn.add(this.Target.get(i));
                    }
                }
            }
        }
        return toReturn;
    }
    /**
     * 
     */
    public void refreshJList1() {
        List<String> temp = this.getRiboswitchTargetByInput();
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < temp.size(); i++) {
            model.addElement(temp.get(i));
        }
        this.riboTargetNameJList.setModel(model);
    }
    /**
     * getAptnameByTarget
     * @param target
     * @return
     */
    public List<String> getAptnameByTarget(String target) {
        List<String> toReturn = new ArrayList<String>();
        for (int i = 0; i < Target.size(); i++) {
            if (Target.get(i).equals(target)) {
                toReturn.add(this.AptName.get(i));
            }
        }
        return toReturn;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        riboswitchTarNameTextField = new javax.swing.JTextField();
        riboswitchTypeComboBox = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        riboGoButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        riboAptamerJList = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        riboTargetNameJList = new javax.swing.JList();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RiboSwitch");

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        riboswitchTarNameTextField.setFont(new java.awt.Font("宋体", 0, 18));
        riboswitchTarNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        riboswitchTarNameTextField.setName("riboswitchTarNameTextField"); // NOI18N
        riboswitchTarNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riboswitchTarNameTextFieldActionPerformed(evt);
            }
        });

        riboswitchTypeComboBox.setUI(new IComboBoxUI());
        riboswitchTypeComboBox.setRenderer(new IComboBoxRenderer());
        riboswitchTypeComboBox.setBackground(java.awt.Color.lightGray);
        riboswitchTypeComboBox.setFont(new java.awt.Font("Arial Black", 0, 14));
        riboswitchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Protein", "Virus", "Enzyme", "Drug", "Small molecule", "Lipid", "Cell", "Dye", "Nucleic acid", "Animo acid", "Antibody", "Chemical compound", "Peptide", "Hormone", "Carbohydrate" }));
        riboswitchTypeComboBox.setToolTipText("<html><BODY STYLE=\"BACKGROUND-COLOR:#FFFFFF;\"><font size=\"4\" face=\"Verdana\">To select the target type</html>"); // NOI18N
        riboswitchTypeComboBox.setName("riboswitchTypeComboBox"); // NOI18N
        riboswitchTypeComboBox.setOpaque(false);
        riboswitchTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riboswitchTypeComboBoxActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(java.awt.Color.white);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Up Regulation");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(java.awt.Color.white);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 14));
        jRadioButton2.setText("Down Regulation");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        riboGoButton1.setFont(new java.awt.Font("Arial Black", 0, 14));
        riboGoButton1.setText("Go!");
        riboGoButton1.setName("riboGoButton1"); // NOI18N
        riboGoButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riboGoButton1MouseClicked(evt);
            }
        });
        riboGoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riboGoButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(10);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 165, 0), 2, true));
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel40.setText("Sequence:");
        jLabel40.setName("jLabel40"); // NOI18N

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        riboAptamerJList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        riboAptamerJList.setFont(new java.awt.Font("宋体", 0, 18));
        riboAptamerJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        riboAptamerJList.setName("riboAptamerJList"); // NOI18N
        riboAptamerJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                riboAptamerJListValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(riboAptamerJList);

        jScrollPane8.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane8.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        //jScrollPane8.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane8.setName("jScrollPane8"); // NOI18N

        riboTargetNameJList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        riboTargetNameJList.setFont(new java.awt.Font("宋体", 0, 18));
        riboTargetNameJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        riboTargetNameJList.setName("riboTargetNameJList"); // NOI18N
        riboTargetNameJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                riboTargetNameJListValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(riboTargetNameJList);
        //jScrollPane8.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        //jScrollPane8.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane8.updateUI();

        jLabel42.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel42.setText("Target Name");
        jLabel42.setName("jLabel42"); // NOI18N

        jLabel43.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel43.setText("Aptamer");
        jLabel43.setName("jLabel43"); // NOI18N

        jPanel16.setBackground(new java.awt.Color(255, 215, 0));
        jPanel16.setName("jPanel16"); // NOI18N

        jLabel39.setBackground(new java.awt.Color(255, 165, 0));
        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel39.setText("Target Type:");
        jLabel39.setName("jLabel39"); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 215, 0));
        jPanel15.setName("jPanel15"); // NOI18N

        jLabel38.setBackground(new java.awt.Color(255, 215, 0));
        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel38.setText("Input your Target:");
        jLabel38.setName("jLabel38"); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(74, 74, 74))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(riboGoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addContainerGap(597, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riboswitchTarNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(riboswitchTypeComboBox, 0, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riboswitchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riboswitchTarNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riboGoButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        //jScrollPane8.updateUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riboswitchTarNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riboswitchTarNameTextFieldActionPerformed

    }//GEN-LAST:event_riboswitchTarNameTextFieldActionPerformed

    private void riboswitchTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riboswitchTypeComboBoxActionPerformed
         String temp=this.riboswitchTarNameTextField.getText();         
		this.refreshJList1();     
		}//GEN-LAST:event_riboswitchTypeComboBoxActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
			this.jRadioButton2.setSelected(!this.jRadioButton2.isSelected());     
		}//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged

    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        this.jRadioButton1.setSelected(!this.jRadioButton1.isSelected());     }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void riboGoButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riboGoButton1MouseClicked
		for (int i = 0; i < AptName.size(); i++) {             
		if (AptName.get(i).equals((String) this.riboAptamerJList.getSelectedValue())) {                 
		this.aptSelect = i;                 
		break;             
		}         
		}         
		this.riboswitch = new Riboswitch(this.Aptseq.get(aptSelect));         
		this.jTextArea1.setText("");         
		if (this.jRadioButton1.isSelected()) {             
		jPanelUp.ShowUpJPG(riboswitch);             
		this.jTextArea1.setText(riboswitch.getON().toUpperCase());         
		}         
		if (this.jRadioButton2.isSelected()) {             
		jPanelUp.ShowDownJPG(riboswitch);             
		this.jTextArea1.setText(riboswitch.getOFF().toUpperCase());         
		}     
	}//GEN-LAST:event_riboGoButton1MouseClicked

    private void riboGoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riboGoButton1ActionPerformed

    }//GEN-LAST:event_riboGoButton1ActionPerformed

    private void riboAptamerJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_riboAptamerJListValueChanged

    }//GEN-LAST:event_riboAptamerJListValueChanged

    private void riboTargetNameJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_riboTargetNameJListValueChanged

        List<String> temp = this.getAptnameByTarget((String) this.riboTargetNameJList.getSelectedValue());         
		DefaultListModel model = new DefaultListModel();         
		for (int i = 0; i < temp.size(); i++) {             
		model.addElement(temp.get(i));         
		}         
		this.riboAptamerJList.setModel(model);     
		}//GEN-LAST:event_riboTargetNameJListValueChanged

    private void jPanel5ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentHidden
 
		}//GEN-LAST:event_jPanel5ComponentHidden

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown

	}//GEN-LAST:event_jPanel5ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riboswitchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riboswitchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riboswitchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riboswitchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new riboswitchJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList riboAptamerJList;
    private javax.swing.JButton riboGoButton1;
    private javax.swing.JList riboTargetNameJList;
    private javax.swing.JTextField riboswitchTarNameTextField;
    private javax.swing.JComboBox riboswitchTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
