/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartFrame.java
 *
 * Created on 2012-8-28, 17:56:50
 */
package org.igem.browser;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JProgressBar;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * To show a jframe that has no title and border
 * @author Guo Jiexin
 */
public class StartFrame extends javax.swing.JFrame implements ChangeListener, ActionListener {

    /** Creates new form StartFrame */
    /**
     * 
     * @param timeToDelay the time that after which the frame will dispose
     */
    Browser browser;

    //close frame
    public void colseFrame() {
        this.dispose();
    }

    public StartFrame(Browser b) {
        browser = b;        
        this.setUndecorated(true);
        initComponents();

        this.setBackground(Color.white);
        this.setLocationRelativeTo(null);//to make the frame center of the screen
        Container container = this.getContentPane(); 
        container.setLayout(null);
        container.add(jProgressBar1);
        new MyTimer();
    }
    @Override
    public void stateChanged(ChangeEvent e) {
    }

    @Override
    public void actionPerformed(ActionEvent e) {
    }

    public class MyTimer {

        public Timer timer;

        public MyTimer() {
            timer = new Timer();
            timer.schedule(new MyTask(), 0, //initial delay 
                    1 * 50); //subsequent rate
        }

        public class MyTask extends TimerTask {

            public void run() {               
                int value = jProgressBar1.getValue();
                if (value <= 100) {
                    value++;                    
                    jProgressBar1.setValue(value);
                } else {
                    colseFrame();
                    //Display the main form
                    browser.setVisible(true);
                    timer.cancel();
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1 = new JProgressBar();
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(101);
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addChangeListener(this);
        jProgressBar1.setPreferredSize(new Dimension(200, 30));
        jProgressBar1.setForeground(new java.awt.Color(0, 102, 255));
        jProgressBar1.setName("jProgressBar1"); // NOI18N
        jProgressBar1.setPreferredSize(new java.awt.Dimension(148, 12));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/igem/browser/beautifulStartForm.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*  try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    break;
    }
    }
    } catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
    java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
    java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    
    /* Create and display the form */
    /*java.awt.EventQueue.invokeLater(new Runnable() {
    
    public void run() {
    new StartFrame().setVisible(true);
    
    }
    });*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    // }
}
